Fix RTL and LTR encoding with Arabic
ethereum/staking-deposit-cli pull request #325
Opened 2023-02-03 21:47 UTC by yorickdowne

This solves #275. 

As per https://stackoverflow.com/questions/65318857/how-to-embed-english-in-right-to-left-languages I am using right-to-left embedding for Arabic, and left-to-right embedding with the separating commas.

I first tried this with `return lambda: '%s %s: ' % (prompt_func(), '['+'\u202a, \u202c'.join(choices)+']')` but this creates non-printing characters when the text is already LTR. Instead, I am now using a more elaborate `for` loop.

Output with this change is correct in my terminal, though I have a hard time copy/pasting that into github 😅 

Trying it as an embedded image

![image](https://user-images.githubusercontent.com/71337066/216716529-f42d9e96-39ae-4f34-80e2-e6e50d7682df.png)

2023-02-03 21:48 UTC, yorickdowne commented
```
Please choose your language [1. ‫العربية‬‪,‬2. ελληνικά, 3. English, 4. Français, 5. Bahasa melayu, 6. Italiano, 7. 日本語, 8. 한국어, 9. Português do Brasil, 10. român, 11. Türkçe, 12. 简体中文]:  [English]:
```

2023-02-08 20:14 UTC, yorickdowne commented
@wackerow Can I ping you for review? Would be nice to have this in with withdrawals release. It's a QoL change that fixes the mangling of the UI language selection choices.

2023-02-08 21:38 UTC, yorickdowne commented
I agree that additional QoL would be great. I don't speak even a little Arabic, so I'm afraid I'd mess things up if I tried. I'd be happy to collab with an Arabic speaker on it, for a separate PR.

2023-02-08 21:40 UTC, yorickdowne commented
Ohhh your Terminal is better than mine. One more change, I'll add an additional space after the embedded-style comma. Also, the for loop is only necessary to deal with wonky Terminals like mine that print an empty char for these embedding characters. I'd still like to keep that for better UX, as not all users have sane Terminals.

2023-02-08 22:37 UTC, wackerow commented
I had already started some work locally to update the Staking Launchpad website as well for better RTL support, and this inspired me to complete it.
Just posted a PR over there https://github.com/ethereum/staking-launchpad/pull/594 that updates the website to fully support a right-to-left layout. Thanks for the nudge @yorickdowne! =)

2023-02-08 22:42 UTC, wackerow approved these changes
<img width="417" alt="image" src="https://user-images.githubusercontent.com/54227730/217667839-02df67ee-b756-4edd-86c2-0e882a00f5fc.png">

Awesome, this looks great!

2023-02-09 04:53 UTC, wackerow requested changes
Hm yeah, I also don't speak the language, but I'm looking closer at this and although my terminal output looked appropriate with how the commas laid out, I don't think it's correct.

If I copy/paste the Arabic text output from my terminal into the shell, it's laid out LTR, but if I paste into Google Translate it rearranges and looks more consistent with how we translate this word on other sites. 

Ethereum.org
<img width="104" alt="image" src="https://user-images.githubusercontent.com/54227730/217720338-9d3cba54-e767-499f-ad2b-956bef1fa2e6.png">

Launchpad:
<img width="77" alt="image" src="https://user-images.githubusercontent.com/54227730/217720365-4e02254f-6c72-4c72-8471-dd47a8198f67.png">

Existing CLI (broken number positioning, but Arabic text is correct)
<img width="248" alt="image" src="https://user-images.githubusercontent.com/54227730/217720686-a7861326-8451-4f01-ae17-bc7b5cc20d44.png">

❌ This PR
<img width="219" alt="image" src="https://user-images.githubusercontent.com/54227730/217720438-e3d33d84-3416-4633-b9f5-934d3b277ddd.png">

Copy output from previous terminal and paste into Google:
<img width="128" alt="image" src="https://user-images.githubusercontent.com/54227730/217720253-99f050c1-cb59-4985-b9aa-c1b8c2ab49c2.png">

I would see this as a blocker given it appears to have flipped the characters. Agree it would be great to get a native speaker to double check this.

2023-02-09 11:34 UTC, yorickdowne commented
Right this is where it gets weird. Let me run this again in my terminal, be back in a jiffy.

2023-02-14 13:23 UTC, yorickdowne commented
![image](https://user-images.githubusercontent.com/71337066/218750734-6cf7339f-f81e-4c96-89d0-8b484407e600.png)

This translates as "Arabic" as per Google translate. It also visually looks like it's flowing.

So there may be Terminal-specific things about how this displays once RTL embedding is there.

I'd like to be cautious and get this right. We can assume that Arabic speakers have their Terminal set up correctly for Arabic, though a few notes in the README would also be good.

Do you have a connection to the gentleperson that did the Arabic translation? I could connect with them, verify how to set up a Terminal "the right way" so it supports RTL, and verify that this code is displaying RTL correctly.

2023-03-14 15:08 UTC, CarlBeek commented
We outsourced the translations and unfortunately don't have a direct connection to the person who did this translation.

2024-08-23 14:06 UTC, closed without merging